### ISSUE TITLE
Incompatible with VanillaBDcraft

### ISSUE THREAD

**Issue by CogentRedTester** [Nuclearfarts/connected-block-textures#6] opened 2020-07-13 15:52 UTC
I'm using the latest version of the mod on 1.16.1. [VanillaBDcraft](https://bdcraft.net/downloads/vanillabdcraft-minecraft/) supports connective textures, and on Optifine they are working:
![optifine](https://user-images.githubusercontent.com/57207260/87324769-bcee5880-c56f-11ea-914b-f91a164b6d43.png)

However, with this mod:
![2020-07-14_01 09 37](https://user-images.githubusercontent.com/57207260/87324879-e27b6200-c56f-11ea-8749-83d24bffe9d4.png)

There are no other mods installed other than the fabric API. 
[Here is the optifine folder inside the resource pack.](https://github.com/Nuclearfarts/connected-block-textures/files/4913553/optifine.zip)

**Comment by TwilightFlower** [comment] 2020-07-14 00:59
Could you upload a log? There may be an error in there that would help shed some light on the cause of this.

**Comment by CogentRedTester** [comment] 2020-07-14 02:19
You were right, there was an error for every connected texture. I load the texture pack at line 283, they start just after:

[latest.log](https://github.com/Nuclearfarts/connected-block-textures/files/4916136/latest.log)

**Comment by TwilightFlower** [comment] 2020-07-14 14:14
Oh, this. I have this fixed locally, just need to push and release. The officially documented way is `block` but optifine silently supports `blocks` as well.

**Comment by TwilightFlower** [comment] 2020-07-30 12:45
Should be fixed in 0.1.1

**Closed as completed by TwilightFlower** 2020-07-30 12:45 UTC
Labels: bug
